version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.14
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - somenetwork
    ports:
      - '9200:9200'
      - '9300:9300'


networks:
  somenetwork:
    external: true